apiVersion: v1
kind: Service
metadata:
  name: chatbot-service-{{ .Values.env }}
spec:
  selector:
    app: chatbot-{{ .Values.env }}
  type: NodePort
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
    nodePort: {{ .Values.nodePort }}