apiVersion: v1
kind: Service
metadata:
  name: redis-service-{{ .Values.env }}
  namespace: default
  labels:
    app: redis-{{ .Values.env }}
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-{{ .Values.env }}