apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment-{{ .Values.env }}
  namespace: default
  labels:
    app: redis-{{ .Values.env }}
spec:
  replicas: 1
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      app: redis-{{ .Values.env }}
  template:
    metadata:
      labels:
        app: redis-{{ .Values.env }}
    spec:
      containers:
      - name: redis
        image: redis:7.4.0-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: env
                operator: In
                values:
                - {{ .Values.env }}
