apiVersion: v1
kind: ServiceAccount
metadata:
  name: chatbot-sa
  annotations:
    iam.gke.io/gcp-service-account: obot-chatbot@{{ .Values.gcp_project_id }}.iam.gserviceaccount.com
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"