services:
  chatbot:
    image: chatbot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - C:\Users\trung\AppData\Roaming\gcloud\application_default_credentials.json:/app/credentials.json
