apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "chatbot-deployment"
spec:
  replicas: 1
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      containers:
      - name: "chatbot"
        image: "us-east1-docker.pkg.dev/$GCP_PROJECT_ID/obot-prod/chatbot:in-use"
      tolerations:
      - key: "env"
        operator: "Equal"
        value: "prod"
        effect: "NoSchedule"
      - key: "env"
        operator: "Equal"
        value: "prod"
        effect: "PreferNoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "env"
                operator: In
                values:
                - "prod"