apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "chatbot-deployment-dev"
spec:
  replicas: 1
  strategy:
    type: "Recreate"
  template:
    spec:
      containers:
      - name: "chatbot"
        image: "us-east1-docker.pkg.dev/$GCP_PROJECT_ID/obot-dev/chatbot:in-use"
      tolerations:
      - key: "env"
        operator: "Equal"
        value: "dev"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "env"
                operator: In
                values:
                - "dev"
