name: Dev CI/CD workflow 

on:
  push:
    branches:
      - dev

jobs:
  dev-workflow:
    uses: ./.github/workflows/workflow-template.yaml
    with:
      env: 'dev'
      dry_run: false
    secrets: inherit
    permissions:
      contents: read
      id-token: write
